### ISSUE TITLE
FTW-Actor-Ask.xnode no longer supports string input

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#100]
It's often nice to have a json string input for FTW-Actor-Ask.xnode, but deserialize the response into data structure.  It seems that capability has gone away.

**Example: configured messages coming from file**
Allowing a json string message input avoids unnecessary mutation away from string only to be serialized under the hood again.

**FTW-Actor-Ask.xnode should:**
- allow json string input
- allow for explicitly specifying the "FTW-Request-Header" element vs using the input label (<- also new functionality since I last pulled)
- respect explicitly specifying the "FTW-Request-Header" element and override the label (if provided)

Notably, FTW-Connector-Core-Ask.vi provides the string interface but is not an xnode (i.e. requires "manual" deserialization).  I get that having a string (non-static message definition) input likely connotes a dynamic response (meaning "not known at edit time" in this case) but this added flexibility could be nice in some cases, such as parsing common elements from a response (think tests or other standard service type requests to actors which peek at common info).

**Comment by jassems** [comment]
Ok, decided this semantic is actually OK, in conjunction with FTW-Connector-Core-Ask.vi.  It would seem nice to unify this into the xnode, provided there was no loss in performance in doing everything under the xnode hood.  But outside of some pain in updating code, I think the semantic is sensical... where it's not too bad to simply deserialize the FTW-Connector-Core-Ask.vi response in cases where it makes sense to statically yank out some things irrespective of the message.

**Comment by JackDunaway** [comment]
The main reason this ability went away is because it truly was "special"; an exception to the rule. This capability has more potential to be much more negative/surprising than slightly positive/refreshing.

It really boils down to just tuning how much syntax sugar and how much API surface area is optimal; not exactly a right answer here, but looks like we're kinda landing in the same place on this one.

Candid feedback like this continues to be especially helpful.

**Comment by jassems** [comment]
**Reopening with inquiries:**
- wondering why a string input is even allowed by the xnode if it cannot meaningfully deal with it
- questioning the value of using the label to specify "FTW-Request-Header"

**Thoughts against using labels as "FTW-Request-Header"**
The idea of treating the label as the "FTW-Request-Header" breaks the json <-> cluster relationship.  Given that JSON is transparent in FTW, it feels like the API should semantically map to that mental model even in abstractions like an xnode.  Using default values can suggest the appropriate structure to the user vs having to tribally know how the label is used.

**Recommendation:**
Barring performance or other issues with xnodes, having a single "Ask" function would be elegant.  FTW-Connector-Core-Ask.vi could be unified into FTW-Actor-Ask.vi, which would:
- accept either string or cluster input for the request message
- if string input: json string where, if created from the input terminal, contains a default string element labeled "FTW-Request-Header" with value "" (empty string)
- if cluster input: cluster where, if created from the input terminal, contains a default string element labeled "FTW-Request-Header" with value "" (empty string)

**Comment by JackDunaway** [comment]
>"accept either string or cluster input for the request message (broken otherwise)"

This is compelling; I like it. It makes the most sense, also.

Technically: within `featherweight\codegen\xnode\actor\ask\FTW-CodeGen-Prototype.vi`, `@FTW-Codegen-RequestStyle` only allows String and Cluster.

The current behavior -- the one you're arguing doesn't make sense -- absolutely doesn't really make sense. How/why was it developed so crummy in the first place? I'm not sure what that guy was thinking ... but it was probably along the lines of the syntax sugar seen in `featherweight\tests\core\FTW-Test-JSON-Deserialize.vi` for deserialization. Yet, for **serialization**, the implicit ability to wrap a single element in an cluster doesn't map as well as for unwrapping a single element during **deserialization**. It's underconstrained anyway -- what would the name of the element be if its label is used for `FTW-Request-Header`?

Thank you for re-opening with a good suggestion; expect this to be the case, unless someone pipes up with a good reason why the current behavior is useful.

**Comment by jassems** [comment]
One clarification... my "recommendation" doesn't technically make sense... the xnode will have a default type on the "request" input, meaning when you create a constant it's going to be either string or cluster, so there'll really only be one default value.  Unless it provided a "mode" which could flop between string and cluster as the default terminal type, where I think it should then still adapt to type when wired, but the mode would allow choosing / exposing a "default value" of either type, perhaps helping to suggest the "right thing" to the user with respect to "FTW-Request-Header".

I think it would also be fine to default the terminal to string and simply note its cluster abilities in documentation as it's pretty straightforward / clear when the json <-> cluster relationship is semantically preserved.

**Comment by jassems** [comment]
Fixed in build [8f89fa2](https://github.com/featherweight/featherweight/commit/8f89fa21defd7dc46834fd244841c960aa0e2c22) however that build does not include [these fixes and updates](https://github.com/featherweight/featherweight/issues/119).
