### ISSUE TITLE
Does ftw_actor_inbox_construct Apply the Linger Option?

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#109]
In ftw_framework.c, it appears that `ftw_actor_inbox_construct` only sets the max receive size option:

`nn_setsockopt(rcs, NN_SOL_SOCKET, NN_RCVMAXSIZE, &max_recv_size, sizeof(max_recv_size));`

Should it also set the linger option, something like:

`nn_setsockopt (rcs, NN_SOL_SOCKET, NN_LINGER, &linger, sizeof (linger));`

It appears linger is passed to the call to `ftw_actor_inbox_construct` in FTW-Inbox-Core-MessageRouter.vi (along with a max receive size), but doesn't seem to be handled?

**Comment by JackDunaway** [comment]
Linger has never really been implemented fully in the underlying library, and as such, is not particularly useful in FTW as well. See: https://github.com/nanomsg/nanomsg/issues/799

Closing for now.
