### ISSUE TITLE
FTW-System-CommandLineExecute.vi invokes a Windows function on any OS

### ISSUE THREAD

**Issue by DavidStaab** [featherweight/featherweight#42]
This VI invokes the "SystemExec_Win" function from LabVIEW but doesn't check which OS it's running on. Calling the VI on an RT Linux target results in this error while trying to deploy code to the target:

> Deploying FTW-System-CommandLineExecute.vi**FTW-System-CommandLineExecute.vi loaded with errors on the target and was closed.
> LabVIEW:  (Hex 0x627) The function name for the LabVIEW:SystemExec_Win:C	 node cannot be found in the library. To correct this error, right-click the Call Library Function Node and select Configure from the shortcut menu. Then choose the correct function name.**

**Comment by wirebirdlabs** [comment]
This particular underlying library call is slated for replacement at some point with `libuv` (http://docs.libuv.org/en/v1.x/process.html#c.uv_spawn)

Using `SystemExec_Win` is brittle and not officially supported.

In the meantime, this should indeed be wrapped in a Conditional Disable.
