### ISSUE TITLE
Clean up branches; switch from `expressions` to `master`

### ISSUE THREAD

**Issue by JackDunaway** [featherweight/featherweight#46]
Note to all who have forked; this repository will soon be switching from the `expressions` branch to `master` as the default branch, and many development branches will be removed.

This is an effort to clean up the repository, but will temporarily break your workflow. To fix things, simply switch to the `master` branch in your local clone.

Comment here if you have any issues after this change is made! I'll keep the issue open for a few days after the switch.

**Comment by wirebirdlabs** [comment]
OK, this change is now implemented. Feel free to prune all your local branches except for `master`, and ping me (privately if needed) with any support getting your working copy to `master`.

Big thanks to @emetzlervsi helping test this process; no hiccups!

**Comment by DavidStaab** [comment]
I pulled HEAD just now, and it looks like it's still pointing to `expressions`. A second pull for `master` imported a different branch that's ahead of HEAD by 3.

![untitled](https://cloud.githubusercontent.com/assets/1372998/14354233/25d1e600-fca2-11e5-9361-c577bb8ea493.png)

**Comment by wirebirdlabs** [comment]
Try pruning remote tracking branches, and also force deleting those branches locally. IIRC, only one branch (of 4-5 or so) needed to be force deleted -- all others were in the `master` lineage.

**Comment by JackDunaway** [comment]
Closing this issue for now; all, feel free to re-open if you run into future trouble.
