### ISSUE TITLE
FTW-Request-Add-Metadata.vi has incorrect documentation.

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#51]
FTW-Request-Add-Metadata.vi documentation currently reads: "Sends a response message back to the requesting client. This message is attempts to send unconditionally of incoming error. Take caution to wire a sanitized error into this function, because it will be repeated back onto the client. Said another way, an error generated while processing the request will be not only thrown on the request handler, but also on the client as well."

This appears to be a copy-paste stay-over from FTW-Request-Reply.vi.

**Comment by JackDunaway** [comment]
Bug. Further, it's probably worthwhile to intentionally clear all VI documentations at this point and start with a fresh slate.
