### ISSUE TITLE
FTW-Test-Actor-Stress.vi Times Out

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#55]
This might confuse some when running FTW tests; FTW-Test-Actor-Stress.vi will time out sometimes depending on resources (ex. running in a trim VM).

Bumping the "HandshakeTimeout" to 2+ seconds - or raising the timeout specification to the front panel - would make this a bit less likely - or more immediately addressable - out of the box.

Same issue with the Supervisor test.

**Comment by JackDunaway** [comment]
The front panel idea is good! Quick word of warning on this test -- it's the one that flushed out all the bugs in LV synchronization primitives (Events, Event Callbacks, and DVRs), so we also can't be certain the timeouts you're seeing aren't just a manifestation of that failure (the failure mode is undefined behavior, so anything goes).

**Comment by JackDunaway** [comment]
This CAR may be fixed in a forthcoming f-patch. Stay tuned ...

**Comment by JackDunaway** [comment]
I'm working on this right now. Stay tuned ...
