### ISSUE TITLE
Move `ftw-kernel` source into this repository?

### ISSUE THREAD

**Issue by JackDunaway** [featherweight/featherweight#56]
Currently, `ftw-kernel` is a separate repository: https://github.com/featherweight/ftw-kernel

All that source used to be here, but was pulled out in order to simplify this repository (e.g., keep it strictly LabVIEW source, and also to avoid needing to clone subrepositories required by ftw-kernel).

That move was made, even knowing: 1) the two repositories would need to remain in lock-step, and 2) the overhead of maintaining two separate repositories. It was decided that the simplicity of keeping this repo "pure LV" was worth these issues.

Should https://github.com/featherweight/ftw-kernel be collapsed once more into this repo?

**Comment by JackDunaway** [comment]
I'm looking to move forward with this after stewing on it a while; any suggestions or concerns?

Also, what would the directory structure look like? (Conversely, what should it *not* look like? e.g., one example is that putting C source into this repository's `src` directory would interfere with the way I oftentimes add this library to an application `.LVProj` file)

**Comment by emetzlervsi** [comment]
Other than the "feels" of having two unique (but inextricably linked) projects in one repo, I think the benefits outweigh the philosophical issues I have with it, which really amount to no actual downsides that I can think of. Branching takes care of sandboxing.

I suggest using a top level directly called `kernel` and not using `src`.

**Comment by JackDunaway** [comment]
I like the top-level directory idea.

**Comment by jassems** [comment]
I also like Eric's idea. You could even name the directory _kernel to sort
of further indicate its underneath the hoodedness.

I'm surprised that hoodedness is actually a word... I'm not seeing red
squigglies under it like one does, for example, under the word squigglies.

**Comment by JackDunaway** [comment]
> not seeing red squigglies

So ... apparently one of my "favorite" things to do is accidentally click this option -- so my dictionary at this point is littered with non-words and misspellings. :P

In related news, I've already begun to push some commits toward this issue, and I'm now working on getting the build as nice as possible -- staging for some updates to SQLite and also nanomsg.

![screen shot 2016-05-13 at 2 29 52 pm](https://cloud.githubusercontent.com/assets/1944203/15259503/40922400-1917-11e6-856f-25b41524cc7e.png)

**Comment by jassems** [comment]
That's it, I'm adding squigglies!

**Comment by JackDunaway** [comment]
Effectively integrated this starting with 6fddf31203be117b9b526aee0a437c86653d767f and the subsequent patches. It's been working nicely for a few days, so I will close this issue for now.
