### ISSUE TITLE
FTW-Actor-Ask.xnode Broken

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#69]
Upon opening a previously happy VI which contained FTW-Actor-Ask.xnode, I found it to be broken on account of that xnode. 

Unfortunately, I poked around and quickly "resolved" the problem by unwiring and rewiring an input (thinking "force a recompile" which indeed seemed to work) vs capturing more information about the situation.

Not sure if this is related but was surprised to find it on ni.com with a conspicuously short note: http://zone.ni.com/reference/en-XX/help/371361M-01/lverror/edxnodegoverninglibrarybroken/

**Comment by JackDunaway** [comment]
Likely also related to https://github.com/featherweight/featherweight/issues/67

**Comment by jassems** [comment]
Just took a quick glance at [#67](https://github.com/featherweight/featherweight/issues/67) and recalled that I did try the following which did not solve the problem:

- saving
- saving, closing, reopening
- recompiling the VI (not rewiring to force recompile the xnode)

I should have captured the error messages :(

**Comment by jassems** [comment]
Just happened again:

Error: "Spawn New Actor Instance 'Spawn New Actor Instance': XNode is not executable"
Details: "This node is not executable because an unexpected error occured during code generation."

Same fix (unwire / rewire a terminal to force the xnode to recompile) worked.

**Comment by jassems** [comment]
Have not seen this in the latest build / commit: ([8f89fa2](https://github.com/featherweight/featherweight/commit/8f89fa21defd7dc46834fd244841c960aa0e2c22)).  Closing.
