### ISSUE TITLE
Replace input/output JSON DVR in all JSON methods with new JSON type

### ISSUE THREAD

**Issue by JackDunaway** [featherweight/featherweight#70]

**Comment by DavidStaab** [comment]
Any more details on what this means? And will there be a compatibility break because of it?

**Comment by JackDunaway** [comment]
I've updated the title for clarity. It's a breaking change, but one that should be simple to fix applications based on compile-time errors (importantly, no new run-time errors should sneak in). The behavior of the entire JSON API will not change at all; only the representation of the JSON object type, moving from a "naked" DVR'ed cluster to the typedef'd JSON type: https://github.com/featherweight/featherweight/tree/master/src/core/type

This move (for all FTW types) enables the Reflection API to unambiguously resolve special FTW types, which enables better XNodes -- such as #15.

It also should make for a better QuickDrop experience, since "FTW JSON" will now enable you to drop an instance of the JSON object type (which should aid the quick job of fixing compiler errors introduced by this commit, with `CTRL+Space`...`ftw json`...`CTRL+P`)
