### ISSUE TITLE
Error 1556 occurs on FTW-Actor-Ask.xnode

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#72]
The following error occurred after renaming / moving files, and then running FBQ-Test-SpawnPublishingActorAndSubscribe.vi to see that things were still working.

<img width="338" alt="screen shot 2016-05-30 at 5 13 44 pm" src="https://cloud.githubusercontent.com/assets/7451453/15659169/f4f5a77e-268b-11e6-8925-ed4edf391101.png">

The error expresses in the top level diagram as seen in the screenshot above, however single-stepping shows it occurs as it executes FTW-Actor-Ask.xnode.  

Furthermore, it shows two small "selections" on the block diagram in what otherwise appears to be white space (one inside a while loop, the other outside, if that's of any significance). If you press the "Stop" button in the error dialog box shown above, those "selections" remain in tact.  If you subsequently hit "delete" in an attempt to remove these "hidden selections" the cursor spins as though it's recompiling (seems to be xnode-ish recompile behavior).

This error persisted after trying the following: (where I opened and ran FBQ-Test-SpawnPublishingActorAndSubscribe.vi after each step below)
- clearing object cache, closing / relaunched LabVIEW
- recompiling the ftw directory and all other source, closing / relaunched LabVIEW

The error disappeared when:
- LabVIEW crashed
- relaunched LabVIEW
- opened / ran FTW-Test-Actor-Stress.vi (worked)
- opened / ran FBQ-Test-SpawnPublishingActorAndSubscribe.vi

Any ideas are welcome to avoid this - or simply resolve it more quickly - in the future are welcome.

**Comment by JackDunaway** [comment]
This definitely sounds like an XNode issue, but it's unclear exactly what's happening. Can you provide a set of steps to reproduce from this repository itself? e.g., an order of operations of moving/renaming one of the tests that would show the same issues?

**Comment by JackDunaway** [comment]
I've tried this sequence, as yet unable to repro what you're seeing:

1. Move `FTW-Test-Actor-Stress.vi` into `dummydir\FTW-Test-Actor-Stress.vi`
2. Open `FTW-Test-Actor-Stress.vi`
3. Relink and run

**Comment by jassems** [comment]
I haven't been able to reproduce it (and it wasn't clear what resolved it),
but will try to do so and report back with steps if successful!

Not sure if related, but there was a warning (in the LabVIEW load details
dialog) that I saw around the time of the error which indicated a "version
update to <version number> from <version number>" <- that's not verbatim
but similar to the language used.

Perhaps that's a scent trail as well... more data to come if I can
reproduce.

**Comment by JackDunaway** [comment]
That load warning is expected for now, but will ideally be replaced -- see #67

**Comment by jassems** [comment]
Experiencing this again and it's more persistent. Stay tuned for updates as I hope to discover how to systematically resolve it when it does occur.  I'd also like to understand when / why it happens to (short term) avoid creating it and (long term) better articulate the steps to reproduce so it can be fixed.

This is a showstopper - if anyone else has seen this or further characterize it, please share :)
