### ISSUE TITLE
WebSocket Not Working with Publisher API

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#85]
**Behavior**
- no error on the LabVIEW side
- attempting to open a websocket connection from a client / browser simply hangs / never fires the websocket onopen() handler
- terminating the VI causes the client's connection attempt to fail as follows: (address and port sanitized below)

_WebSocket connection to 'ws://address:port/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED_

Could be a simple configuration issue on the client / browser side. For example, is there a new "type" which should be used in the javascript instantiation: 

`new WebSocket(address, type);`

Currently using the old "x-nanomsg-sub".

Here's a pic of the simple tester VI:

<img width="759" alt="screen shot 2016-06-17 at 7 42 02 pm" src="https://cloud.githubusercontent.com/assets/7451453/16168062/d1e440b0-34c3-11e6-9283-44aa34bac755.png">

Made send timeout and linger super generous *just in case* but still no love.

Note: the old FTW API still works, so this shouldn't be a networking / VM issue.

**Comment by jassems** [comment]
**Solved**
Dove into the ftw-kernel-nanomsg source and found the list of types in [ws_handshake.c](https://github.com/featherweight/ftw-kernel-nanomsg/blob/master/src/transports/ws/ws_handshake.c)

For convenience, here they are:

`static const struct nn_ws_sp_map NN_WS_HANDSHAKE_SP_MAP[] = {
    { NN_PAIR,       NN_PAIR,       "pair.sp.nanomsg.org" },
    { NN_REQ,        NN_REP,        "req.sp.nanomsg.org" },
    { NN_REP,        NN_REQ,        "rep.sp.nanomsg.org" },
    { NN_PUB,        NN_SUB,        "pub.sp.nanomsg.org" },
    { NN_SUB,        NN_PUB,        "sub.sp.nanomsg.org" },
    { NN_SURVEYOR,   NN_RESPONDENT, "surveyor.sp.nanomsg.org" },
    { NN_RESPONDENT, NN_SURVEYOR,   "respondent.sp.nanomsg.org" },
    { NN_PUSH,       NN_PULL,       "push.sp.nanomsg.org" },
    { NN_PULL,       NN_PUSH,       "pull.sp.nanomsg.org" },
    { NN_BUS,        NN_BUS,        "bus.sp.nanomsg.org" }
};`

**Comment by JackDunaway** [comment]
Thanks for the detailed report, and glad you found a fix!

If in your testing, you're able to extract a small example/test, that'd be great to upstream. Just point me to any given commit/branch in your fork and that's enough to cherry-pick and mainline.

**Comment by jassems** [comment]
Sounds good, will do.  I have a few things to which to point you that may
be of interest for mainline, such as (haven't curated yet so possibly more):

   - examples
   - added "<UpDir>" and several aliases to resolve symbolic paths
   - multisubscriber socket API
   - added GetInboxAddress to Connector API (there are cases where it's
   nice to have this, such as managing a list of inbox connections and needing
   to dynamically remove by address)

In many cases I've kept things separate from FTW for the moment so that I
could gracefully adopt changes, but those you're interested in I'll merge
and relink accordingly.
