### ISSUE TITLE
Update WebSocket Client Open Connection Failure Mode for Invalid Type

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#86]
Related to [#85](https://github.com/featherweight/featherweight/issues/85)

Client open connection simply hangs if you specify an invalid "type".

Let's explicitly refuse the connection when an invalid connection "type" is specified if possible to generate an error on the client.

**Comment by JackDunaway** [comment]
This issue actually applies to the old Socket API; can you try it with the latest at https://github.com/featherweight/featherweight/commit/de100884c4dd3a278a5ea7e56352c700381ca2d8?

Try starting with with this new API for the Publisher socket type: https://github.com/featherweight/featherweight/tree/master/src/socket/publisher

**Comment by jassems** [comment]
Indeed, at the very least this is fixed in the latest commit ([8f89fa2](https://github.com/featherweight/featherweight/commit/8f89fa21defd7dc46834fd244841c960aa0e2c22)).  It now returns error 42 with a nice message indicating the address is malformed.
