### ISSUE TITLE
FTW-Actor-Ask.xnode Doesn't Work With Boolean Type (And Possibly Other Non-Composite Types)

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#88]
I discovered this when using a style similar to that in FTW-Connector-SendPoisonPill.vi (shown below as an example of the problem) where I wanted to pluck a single value from a response.  It returns without error but errantly always returns the value false.  It does not generate an error.

**Not Working**
<img width="824" alt="screen shot 2016-06-22 at 12 46 30 am" src="https://cloud.githubusercontent.com/assets/7451453/16255949/007e6c68-3814-11e6-8e9f-d51769a537fa.png">

**Simple Workaround**
<img width="817" alt="screen shot 2016-06-22 at 12 47 33 am" src="https://cloud.githubusercontent.com/assets/7451453/16255965/11b52256-3814-11e6-879b-176aea5d3de0.png">

I suspect the fix is relatively straightforward in the xnode source.

**Comment by JackDunaway** [comment]
I think this syntax is already supported ... have you tried upgrading to the latest at 54a42a6?

Here's my quick (and dirty) sanity check -- codegen results on top, scratch VI on bottom:

![screen shot 2016-06-22 at 8 47 48 am](https://cloud.githubusercontent.com/assets/1944203/16268995/3a4c752e-3856-11e6-86cc-ee9a253ffe74.png)

**Comment by JackDunaway** [comment]
Regardless whether it works; the action item here is to create a test of this syntax sugar to ensure coverage.

**Comment by jassems** [comment]
I'm on a version from back in April... will checkout updates to see what I
can pull, awesome if it's already fixed!

**Comment by jassems** [comment]
Fixed in build / commit [8f89fa2](https://github.com/featherweight/featherweight/commit/8f89fa21defd7dc46834fd244841c960aa0e2c22).
