### ISSUE TITLE
Actors do not receive browser client messages via WebSocket

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#98]
It appears that Actor inboxes can host more than one endpoint: FTW-Inbox-Core-Configuration.vi expects a flat "AdditionalServiceEndpoints" object containing key / value pairs where keys can be anything (they are iterated) and values are addresses.

I'd hoped this would allow me to configure an additional actor endpoint as a websocket address and then send it messages via a browser, however attempting to open a connection from the browser renders the following error: 

**"WebSocket connection to 'ws://address:port' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
test.js:65 A websocket error occurred: (WebSocket onerror event data not received.)"**

where "address" and "port" have the corresponding ip address and port to which we're attempting to open a connection.

**Is this feature implemented in ftw32.dll, or is the interface simply stubbed for the future?  If implemented, can someone point to a commit?**

Admittedly I did not go looking in the ftw32.dll source to explore further.

**Comment by JackDunaway** [comment]
This feature should be available, but it's only had brief testing a while back. It may not be working correctly anymore since a lot has changed.

Are you explicitly choosing a port? One constraint for these additional endpoints is that they cannot dynamically choose their own port (e.g., `ws://127.0.0.1:*` would fail, since wildcards are intentionally not allowed here).

What happens if you try your same setup, but using the `ws` address as the primary `InboxAddress`?

**Comment by JackDunaway** [comment]
PS: here is the kernel code that iterates thru the array of addresses and binds: https://github.com/featherweight/featherweight/blob/6e71163c1bf4c756f97226b2a187fe75236b838d/kernel/framework/ftw_framework.c#L175-L184

**Comment by jassems** [comment]
Hey, thanks for the notes, here are responses:

>Are you explicitly choosing a port?
Yes, tried a few addresses (exs. ws://127.0.0.1:9998, ws://<adapter ip>:9998) as well as a few ports just in case.

>What happens if you try your same setup, but using the ws address as the primary InboxAddress?
Instead of the client / browser failing with the "ERR_CONNECTION_REFUSED" error (which does fire the socket "onerror" event - with no error data - followed by the "onclose" event), it simply doesn't open the connection and doesn't fire onerror.

**Comment by jassems** [comment]
PS - I originally tried several socket types however from the code linked above (thanks!) it appeared that NN_REP was used and therefore on the client side my latter connection attempts were with type type "rep.sp.nanomsg.org".

Question: I presume the additional service endpoints event into LabVIEW the same way (perhaps with lower priority according to some notes in the FTW Inbox API).

Also, I'm on a version of FTW from March 30 (commit a54d782).  There's at least one change to connector in my branch which will require updates when upgrading.  I'd like to do this before the next big project but can't take on the risk to current projects.  Still need to vet the other commits.  Any chance there's a readme or perhaps a view in on github or sourcetree that would make reading through the commit history elegant (i.e. some nicely concatenated version of all the commits)?

**Comment by JackDunaway** [comment]
> on the client side my latter connection attempts were with type type "rep.sp.nanomsg.org"

So, it is working now?

> a readme or perhaps a view in on github or sourcetree that would make reading through the commit history elegant

The Log/History in Sourcetree works pretty well interactively browsing the commits. Also, I've updated #74 with details. There will be a few more breaking changes between now and 1.0.0-alpha, but after that point such changes/fixes between versions should be kept in a RELEASES document.

**Comment by jassems** [comment]
> So, it is working now?

Unfortunately still not working, just wanted to be clear about the "types" with which I had attempted to connect, and specifically that I'd tried to connect using the type which I think the additional service endpoint is expecting based on linked kernel code.

**Comment by JackDunaway** [comment]
Aha; try `req.sp.nanomsg.org ` client-side, the pair to REP actor-side

**Comment by jassems** [comment]
Had tried that as well, but still no love :(

As as aside on which connection type might be required on the client side, the publisher API is working with the client / browser using type `pub.sp.nanomsg.org` not `sub.sp.nanomsg.org` to connect to the PUB actor-side successfully.  Thus, it seems as though the "connect" semantic on the client side is happy with simply connecting to server-side the bound type (vs pairing it, at least in the case of an actor-side publisher)?

**Comment by jassems** [comment]
Back on this... just went through the paces with the same results.

**Observations:**
- in current tests, the "InboxConfiguration" element "AdditionalServiceEndpoints" is deserialized correctly, making it all the way to the "ftw_socket_inbox_construct" call within "FTW-Inbox-Core-MessageRouter.vi"
- "ftw_socket_inbox_construct" creates a REP socket and "ftw_nanomsg_connector_connect" (which creates the connection for FTW "Ask" functions in LabVIEW) creates a pairing REQ socket as observed in the ftw kernel
- "additional endpoints" are constructed the same way as the primary inbox address, implying a REQ socket is appropriate for browser clients connecting to the actor
- a primary inbox address set to ws://*:* works with LV-LV communciation; able to send and receive messages as expected to that actor with a ws:// primary inbox address

**Problems:**
- using a REQ socket "hangs" in the sense that when you attempt to open the WebSocket connection `ws = new WebSocket(wsAddress, wsType);` where wsType is `"req.sp.nanomsg.org"`, none of the expected handlers fire (ex. onopen or onerror).
- using a REP socket opens the WebSocket connection `ws = new WebSocket(wsAddress, wsType);` where wsType is `"rep.sp.nanomsg.org"`, DOES open the connection successfully and fires the onopen handler, however sending messages from the browser to the actor using `ws.send("<stuff>");` does not reach the actor.  Even if it did, I would expect it to fail on reply because it wouldn't have included FTW-Reply-MsgControl (which should probably just be transparent in JSON vs base64 encoding it, simply wrapped into its own sub-object, just some booleans, a couple integers, and an ActorStatus json object which can be serialized). 
- SEE DETAILS BELOW FOR POSSIBLE SYNTHESIS ON PROBLEMS

**Synthesis**
This might all make sense.  WebSocket creation in the browser may be validating against response headers (it connects to the URL, which replies with headers containing one or more acceptable "types", and the browser checks that the type or types you attempted to open with are a subset of those in the response header).  In fact, this may be the fundamental incongruence with how WebSocket works from the browser's perspective and how FTW is expecting requests to arrive (more specifically, what headers it's expecting requests to carry). 

Said differently, could it be that the kernel code for handling incoming actor messages is simply rejecting messages that come from the browser because the kernel is expecting requests to carry the header type `"req.sp.nanomsg.org"` and not `"rep.sp.nanomsg.org"`?  

**Solutions?**
If the browser can only properly open the connection in congruence with the headers it receives from the actor (in this case `"rep.sp.nanomsg.org"`) then perhaps the actor (kernel) can either:
- send `"req.sp.nanomsg.org"` and `"rep.sp.nanomsg.org"` as valid types in the response headers for a ws:// connection request
- accept incoming ws:// messages with header `"rep.sp.nanomsg.org"`


Thoughts on this?  I'd like to get this working and fleshed out asap; let me know how I can help!

**Comment by jassems** [comment]
Solved (thanks for the debug sessions Jack!)

**Opening Connections**
- the browser "open connection" must match server's ws type
- example: to open a connection to a FTW actor with inbox address of form `ws://<address>:<port>` (which binds / creates a `rep.sp.nanomsg.org` socket), we would use the following javascript: `var ws = new WebSocket('ws://<address>:<port>, 'rep.sp.nanomsg.org');`
- this is supported by nanomsg documentation here: https://github.com/nanomsg/nanomsg/blob/master/rfc/sp-websocket-mapping-01.txt

"For example, an NN_REQ client socket, connecting to an NN_REP server,
   will send the value rep.sp.nanomsg.org in the Sec-WebSocket-Protocol
   field.  The NN_REP socket on the server would then include the same
   rep.sp.nanomsg.org in its response."

- this is notable as often socket types are "paired" where, for example, one would open a "sub" socket to receive messages from a "pub" socket

**WebSocket Binary Type**
- a `binarytype` must be specified on ws connections as either `arraybuffer` (array of bytes) or `blob` (<- used for sending DOM objects).  FTW sends and expects messages as `arraybuffer`
- use `ws.binaryType = "arraybuffer";` just after connecting to specify this

**Sending Messages (Request-Response)**
- to send a message to an actor inbox (or a configured "additional endpoint address"), one must respect the nanomsg protocol within for request-response sockets 
- more specifically, messages must include a small 4-byte header where the most significant bit of the 32 bits must be 1
- this header is used as a unique ID to correlate responses to their original requests (accounts for the fact that responses may be received out of order)
- you'll need to send this header and strip it from received messages

**Error on ws.close()**
- there's a persistent browser-side error on `ws.close()` which does not have any known negative functional implications, but is perhaps noteworthy
- console error message: `WebSocket connection to 'ws://<address>:<port>/' failed: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0`
- this may be related to or similar to: https://forum.eset.com/topic/8355-protocol-filtering-breaks-websockets-after-update-at-5052016/

**Comment by jassems** [comment]
See previous comment, this issue is resolved.

**Comment by jassems** [comment]
Solved (thanks for the debug sessions Jack!)

**Opening Connections**
- the browser "open connection" must match server's ws type
- example: to open a connection to a FTW actor with inbox address (or additional service endpoint address) of form `ws://<address>:<port>` (which binds / creates a `rep.sp.nanomsg.org` socket), we would use the following javascript: `var ws = new WebSocket('ws://<address>:<port>', 'rep.sp.nanomsg.org');`
- this is supported by nanomsg documentation here: (near line 102) https://github.com/nanomsg/nanomsg/blob/master/rfc/sp-websocket-mapping-01.txt
- this is notable as one might expect to "pair" the socket where, for example, one might open a "sub" socket to receive messages from a "pub" socket

**WebSocket Binary Type**
- a `binarytype` must be specified on ws connections as either `arraybuffer` (array of bytes) or `blob` (<- used for sending DOM objects).  FTW sends and expects messages as `arraybuffer`
- use `ws.binaryType = "arraybuffer";` just after connecting to specify this

**Sending Messages (Request-Response)**
- to send a message to an actor inbox (or a configured "additional endpoint address"), one must respect the nanomsg protocol within for request-response sockets 
- more specifically, messages MUST be UTF-8 encoded and include a 4-byte header where the most significant bit (MSB) of the 32 bits must be 1 (this header is used as a unique ID to correlate responses to their original requests; accounts for the fact that responses may be received out of order)
- you'll need to prepend this header before sending messages, and then strip (and nominally validate) it for received messages
- one strategy for this is to use two 2-byte UTF-8 characters to represent the header
- fortunately, the UTF-8 representation for ALL 2-byte characters satisfies the MSB condition, as shown here: 110xxxxx 10xxxxxx where the x's represent the code point bits (see [wikipedia's UTF-8 entry](https://en.wikipedia.org/wiki/UTF-8) for more details)
- it's important to note however that only unicode characters in the range U+0080 to U+07FF will be encoded with 2-bytes as UTF-8 (so we must select two such characters to ensure we get our 4-byte header)
- it's also important to note that javascript uses UTF-16 encoding (which for now just means when we use unicode characters to define our string)
- thus, we can append two characters (remember they will be 2-bytes each) in the range noted above as our "message header"
- example message with header: `var msg = "\u0080\u0080"+'{"FTW-Request-Header":"Test", "Data":"blah"}';`
- example of UFT-8 encoding the message for sending: `var buffer = new TextEncoder('utf-8').encode("\u0080\u0080"+'{"FTW-Request-Header": "Test", "Data": "blah"}');` (we could now use `ws.send(buffer);` to send the message and our `ws.onmessage` handler would receive the reply, which will include our header)
- example of ws.onmessage handler stripping the header: `ws.onmessage = function(event){console.log(new TextDecoder('utf-8').decode(new Uint8Array(event.data)).substring(2));};`
- see nanomsg documentation for more details: (near line 376) https://github.com/nanomsg/nanomsg/blob/master/rfc/sp-request-reply-01.txt

**Error on ws.close()**
- there's a persistent browser-side error on `ws.close()` which does not have any known negative functional implications, but is noteworthy
- console error message: `WebSocket connection to 'ws://<address>:<port>/' failed: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0`
- **possible cause:** not receiving the proper response payload on close()
- see [101](https://github.com/featherweight/featherweight/issues/101) where this issue has been opened formally

**Comment by jassems** [comment]
Solved (thanks for the debug sessions Jack!)

**Opening Connections**
- the browser "open connection" must match server's ws type
- example: to open a connection to a FTW actor with inbox address (or additional service endpoint address) of form `ws://<address>:<port>` (which binds / creates a `rep.sp.nanomsg.org` socket), we would use the following javascript: `var ws = new WebSocket('ws://<address>:<port>', 'rep.sp.nanomsg.org');`
- this is supported by nanomsg documentation here: (near line 102) https://github.com/nanomsg/nanomsg/blob/master/rfc/sp-websocket-mapping-01.txt
- this is notable as one might expect to "pair" the socket where, for example, one might open a "sub" socket to receive messages from a "pub" socket

**WebSocket Binary Type**
- a `binarytype` must be specified on ws connections as either `arraybuffer` (array of bytes) or `blob` (<- used for sending DOM objects).  FTW sends and expects messages as `arraybuffer`
- use `ws.binaryType = "arraybuffer";` just after connecting to specify this

**Sending Messages (Request-Response)**
- to send a message to an actor inbox (or a configured "additional endpoint address"), one must respect the nanomsg protocol within for request-response sockets 
- more specifically, messages MUST be UTF-8 encoded and include a 4-byte header where the most significant bit (MSB) of the 32 bits must be 1 (this header is used as a unique ID to correlate responses to their original requests; accounts for the fact that responses may be received out of order)
- you'll need to prepend this header before sending messages, and then strip (and nominally validate) it for received messages
- one strategy for this is to use two 2-byte UTF-8 characters to represent the header
- fortunately, the UTF-8 representation for ALL 2-byte characters satisfies the MSB condition, as shown here: 110xxxxx 10xxxxxx where the x's represent the code point bits (see [wikipedia's UTF-8 entry](https://en.wikipedia.org/wiki/UTF-8) for more details)
- it's important to note however that only unicode characters in the range U+0080 to U+07FF will be encoded with 2-bytes as UTF-8 (so we must select two such characters to ensure we get our 4-byte header)
- it's also important to note that javascript uses UTF-16 encoding (which for now just means when we use unicode characters to define our string)
- thus, we can append two characters (remember they will be 2-bytes each) in the range noted above as our "message header"
- example message with header: `var msg = "\u0080\u0080"+'{"FTW-Request-Header":"Test", "Data":"blah"}';`
- example of UFT-8 encoding the message for sending: `var buffer = new TextEncoder('utf-8').encode("\u0080\u0080"+'{"FTW-Request-Header": "Test", "Data": "blah"}');` (we could now use `ws.send(buffer);` to send the message and our `ws.onmessage` handler would receive the reply, which will include our header)
- example of ws.onmessage handler stripping the header: `ws.onmessage = function(event){console.log(new TextDecoder('utf-8').decode(new Uint8Array(event.data)).substring(2));};`
- see nanomsg documentation for more details: (near line 376) https://github.com/nanomsg/nanomsg/blob/master/rfc/sp-request-reply-01.txt

**Error on ws.close()**
- there's a persistent browser-side error on `ws.close()` which does not have any known negative functional implications, but is noteworthy
- console error message: `WebSocket connection to 'ws://<address>:<port>/' failed: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0`
- **possible cause:** not receiving the proper response payload on close()
- see [101](https://github.com/featherweight/featherweight/issues/101) where this issue has been opened formally
